const REACT_APP_BASE_API_URL =
  "https://76d2-2001-ee0-167-409d-45e-d6e0-6953-7c74.ngrok-free.app";
const PROBLEM_STATUS = ["ALL", "SOLVED", "TODO", "ATTEMPTED"];
const PROBLEM_DIFFICULTY = ["ALL", "EASY", "NORMAL", "HARD"];
const RESPONSE_STATUS = {
  Ok: 200,
  Created: 201,
  Bad_Request: 400,
};
export {
  REACT_APP_BASE_API_URL,
  PROBLEM_STATUS,
  PROBLEM_DIFFICULTY,
  RESPONSE_STATUS,
};
